# Generated by Django 6.1 on 2026-08-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpqrs',
            name='attachment',
        ),
        migrations.CreateModel(
            name='PQRSAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pqrs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pqrs.ticketpqrs')),
            ],
        ),
    ]
