# Generated by Django 6.1 on 2026-08-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_remove_ticketpqrs_attachment_pqrsattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=1000)),
            ],
        ),
    ]
